apiVersion: v1
kind: Service
metadata:
  name: web-service-v4
  labels:
    app: web-deployment
spec:
  selector:
    app: web-deployment
    version: v4
  ports:
  - name: http-metrics
    protocol: TCP
    port: 8090
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-deployment
  name: web-deployment-v4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment
      version: v4
  template:
    metadata:
      labels:
        app: web-deployment
        version: v4
    spec:
      containers:
      - image: nginx
        name: web
        ports:
        - containerPort: 8080

